# Generated by Django 3.1.6 on 2021-03-06 09:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TickerNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 3, 6, 9, 2, 54, 389317, tzinfo=utc))),
            ],
        ),
    ]
