# Generated by Django 3.1.6 on 2021-03-06 09:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticker_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickernews',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 9, 3, 46, 205086, tzinfo=utc)),
        ),
    ]
