# Generated by Django 3.1.6 on 2021-03-06 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticker_news', '0003_auto_20210306_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickernews',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
