# Generated by Django 3.1.6 on 2021-02-15 10:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbols', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
                ('weights', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('budgets', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('balances', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('total_budget', models.FloatField()),
                ('total_balance', models.FloatField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
    ]
