# Generated by Django 3.1.6 on 2021-02-16 03:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='creat_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='updated_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
