# Generated by Django 3.1.6 on 2021-02-16 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_auto_20210216_0350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='creat_time',
            new_name='created_time',
        ),
    ]
