# Generated by Django 3.1.6 on 2021-02-16 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_auto_20210216_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='balances',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='total_balance',
        ),
    ]
