from rest_framework import serializers
from overviews.models import Overview


class OverviewSerializer(serializers.ModelSerializer):
    class Meta:
        model = Overview

        fields = (
            'id',
            'symbol',
            'asset_type',
            'name',
            'description',
            'exchange',
            'currency',
            'sector',
            'industry',
            'full_time_employees',
            'fiscal_year_end',
            'latest_quarter',
            'market_capitalization',
            'ebitda',
            'pe_ratio',
            'peg_ratio',
            'book_value',
            'dividend_per_share',
            'dividend_yield',
            'eps',
            'revenue_per_share_ttm',
            'profit_margin',
            'operating_margin_ttm',
            'return_on_assets_ttm',
            'return_on_equity_ttm',
            'revenue_ttm',
            'gross_profit_ttm',
            'diluted_eps_ttm',
            'quarterly_earning_growth_yoy',
            'quarterly_revenue_growth_yoy',
            'analyst_target_price',
            'trailing_pe',
            'forward_pe',
            'price_to_sales_ratio_ttm',
            'price_to_book_ratio',
            'ev_to_revenue',
            'ev_to_ebitda',
            'beta',
            'p52_week_high',
            'p52_week_low',
            'p50_day_moving_average',
            'p200_day_moving_average',
            'shares_outstanding',
            'shares_float',
            'shares_short',
            'shares_short_prior_month',
            'short_ratio',
            'short_percent_outstanding',
            'short_percent_float',
            'percent_insiders',
            'percent_institutions',
            'forword_annual_dividend_rate',
            'forword_annual_dividend_yield',
            'payout_ratio',
            'dividend_date',
            'exdividend_date',
            'last_split_factor',
            'last_split_date'
        )