# Generated by Django 3.1.6 on 2021-02-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenClose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=100, unique=True)),
                ('tdate', models.DateTimeField()),
                ('symbol', models.CharField(max_length=10)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volumne', models.BigIntegerField()),
                ('afterHours', models.FloatField()),
                ('preMarket', models.FloatField()),
            ],
        ),
    ]
