# Generated by Django 3.1.6 on 2021-02-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='', max_length=10)),
                ('report_type', models.CharField(default='', max_length=255)),
                ('fiscal_date_ending', models.DateTimeField(default='1900-01-01')),
                ('reported_currency', models.CharField(default='USD', max_length=255)),
                ('total_assets', models.FloatField(default=0.0)),
                ('intangible_assets', models.FloatField(default=0.0)),
                ('earning_assets', models.FloatField(default=0.0)),
                ('other_current_assets', models.FloatField(default=0.0)),
                ('total_liabilities', models.FloatField(default=0.0)),
                ('total_shareholder_equity', models.FloatField(default=0.0)),
                ('deferred_long_term_liabilities', models.FloatField(default=0.0)),
                ('other_current_liabilities', models.FloatField(default=0.0)),
                ('common_stock', models.FloatField(default=0.0)),
                ('retained_earnings', models.FloatField(default=0.0)),
                ('other_liabilities', models.FloatField(default=0.0)),
                ('goodwill', models.FloatField(default=0.0)),
                ('other_assets', models.FloatField(default=0.0)),
                ('cash', models.FloatField(default=0.0)),
                ('total_current_liabilities', models.FloatField(default=0.0)),
                ('short_term_debt', models.FloatField(default=0.0)),
                ('current_long_term_debt', models.FloatField(default=0.0)),
                ('other_shareholder_equity', models.FloatField(default=0.0)),
                ('property_plant_equipment', models.FloatField(default=0.0)),
                ('total_current_assets', models.FloatField(default=0.0)),
                ('long_term_investment', models.FloatField(default=0.0)),
                ('net_tangible_assets', models.FloatField(default=0.0)),
                ('short_term_investment', models.FloatField(default=0.0)),
                ('net_receivables', models.FloatField(default=0.0)),
                ('long_term_debt', models.FloatField(default=0.0)),
                ('inventory', models.FloatField(default=0.0)),
                ('accounts_payable', models.FloatField(default=0.0)),
                ('total_permanent_equity', models.FloatField(default=0.0)),
                ('additional_paid_in_capital', models.FloatField(default=0.0)),
                ('common_stock_total_equity', models.FloatField(default=0.0)),
                ('preferred_stock_total_equity', models.FloatField(default=0.0)),
                ('retained_earnings_total_equity', models.FloatField(default=0.0)),
                ('treasury_stock', models.FloatField(default=0.0)),
                ('accumulated_amortization', models.FloatField(default=0.0)),
                ('other_non_current_assets', models.FloatField(default=0.0)),
                ('deferred_long_term_aseet_charges', models.FloatField(default=0.0)),
                ('total_non_current_assets', models.FloatField(default=0.0)),
                ('capital_lease_obligations', models.FloatField(default=0.0)),
                ('total_long_term_debt', models.FloatField(default=0.0)),
                ('other_non_current_liabilities', models.FloatField(default=0.0)),
                ('deferred_long_term_asset_charges', models.FloatField(default=0.0)),
                ('total_non_current_liabilities', models.FloatField(default=0.0)),
                ('negative_goodwill', models.FloatField(default=0.0)),
                ('warrants', models.FloatField(default=0.0)),
                ('preferred_stock_redeemable', models.FloatField(default=0.0)),
                ('capital_surplus', models.FloatField(default=0.0)),
                ('liabilities_and_shareholder_equity', models.FloatField(default=0.0)),
                ('cash_and_short_term_investments', models.FloatField(default=0.0)),
                ('accumulated_depreciation', models.FloatField(default=0.0)),
                ('common_stock_shares_outstanding', models.FloatField(default=0.0)),
            ],
        ),
    ]
