# Generated by Django 3.1.6 on 2021-02-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_statements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='fiscal_year',
            field=models.CharField(default='1900-01-01', max_length=10),
        ),
    ]
