# Generated by Django 3.1.6 on 2021-02-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.CharField(max_length=10),
        ),
    ]
