# Generated by Django 3.1.6 on 2021-02-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlisttosymbol',
            old_name='watchlist_id',
            new_name='watchlist_name',
        ),
        migrations.AddField(
            model_name='watchlisttosymbol',
            name='user_id',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
