# Generated by Django 3.1.6 on 2021-02-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0002_remove_watchlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='user_id',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
