# Generated by Django 3.1.6 on 2021-02-27 09:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0003_watchlist_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='symbol',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
        ),
    ]
