# Generated by Django 3.1.6 on 2021-02-27 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0004_auto_20210227_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='symbol',
            new_name='symbols',
        ),
    ]
