# Generated by Django 3.1.6 on 2021-02-27 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0005_auto_20210227_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='is_deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
