# Generated by Django 3.1.6 on 2021-02-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0007_watchlist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='is_default',
            field=models.BooleanField(default=0),
        ),
    ]
