# Generated by Django 3.1.6 on 2021-02-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overviews', '0001_initial'),
        ('watchlists', '0008_watchlist_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='symbols',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='symbols',
            field=models.ManyToManyField(to='overviews.Overview'),
        ),
    ]
