# Generated by Django 3.1.6 on 2021-02-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0009_auto_20210227_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='symbols',
        ),
    ]
