# Generated by Django 3.1.6 on 2021-03-06 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticker',
            old_name='ticker',
            new_name='symbol',
        ),
    ]
