# Generated by Django 3.1.6 on 2021-03-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0003_ticker_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='symbol',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
