# Generated by Django 3.1.6 on 2021-03-06 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0004_auto_20210306_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
