from rest_framework import serializers
from balance_statements.models import BalanceSheet


class BalanceSheetSerializer(serializers.ModelSerializer):
    class Meta:
        model = BalanceSheet

        fields = (
            'id',
            'symbol',
            'report_type',
            'reported_currency',
            'fiscal_date_ending',
            'total_assets',
            'intangible_assets',
            'earning_assets',
            'other_current_assets',
            'total_liabilities',
            'total_shareholder_equity',
            'deferred_long_term_liabilities',
            'other_current_liabilities',
            'common_stock',
            'retained_earnings',
            'other_liabilities',
            'goodwill',
            'other_assets',
            'cash',
            'total_current_liabilities',
            'short_term_debt',
            'current_long_term_debt',
            'other_shareholder_equity',
            'property_plant_equipment',
            'total_current_assets',
            'long_term_investment',
            'net_tangible_assets',
            'short_term_investment',
            'net_receivables',
            'long_term_debt',
            'inventory',
            'accounts_payable',
            'total_permanent_equity',
            'additional_paid_in_capital',
            'common_stock_total_equity',
            'preferred_stock_total_equity',
            'retained_earnings_total_equity',
            'treasury_stock',
            'accumulated_amortization',
            'other_non_current_assets',
            'deferred_long_term_aseet_charges',
            'total_non_current_assets',
            'capital_lease_obligations',
            'total_long_term_debt',
            'other_non_current_liabilities',
            'deferred_long_term_asset_charges',
            'total_non_current_liabilities',
            'negative_goodwill',
            'warrants',
            'preferred_stock_redeemable',
            'capital_surplus',
            'liabilities_and_shareholder_equity',
            'cash_and_short_term_investments',
            'accumulated_depreciation',
            'common_stock_shares_outstanding'
        )