# Generated by Django 3.1.6 on 2021-02-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(default='', max_length=100, unique=True)),
                ('symbol', models.CharField(default='', max_length=255)),
                ('asset_type', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('exchange', models.CharField(default='', max_length=255)),
                ('currency', models.CharField(default='', max_length=255)),
                ('sector', models.CharField(default='', max_length=255)),
                ('industry', models.CharField(default='', max_length=255)),
                ('full_time_employees', models.CharField(default='', max_length=255)),
                ('fiscal_year_end', models.CharField(default='', max_length=255)),
                ('latest_quarter', models.DateTimeField(null=True)),
                ('market_capitalization', models.BigIntegerField(null=True)),
                ('ebitda', models.BigIntegerField(null=True)),
                ('pe_ratio', models.FloatField(null=True)),
                ('peg_ratio', models.FloatField(null=True)),
                ('book_value', models.FloatField(null=True)),
                ('dividend_per_share', models.FloatField(null=True)),
                ('dividend_yield', models.FloatField(null=True)),
                ('eps', models.FloatField(null=True)),
                ('revenue_per_share_ttm', models.FloatField(null=True)),
                ('profit_margin', models.FloatField(null=True)),
                ('operating_margin_ttm', models.FloatField(null=True)),
                ('return_on_assets_ttm', models.FloatField(null=True)),
                ('return_on_equity_ttm', models.FloatField(null=True)),
                ('revenue_ttm', models.BigIntegerField(null=True)),
                ('gross_profit_ttm', models.BigIntegerField(null=True)),
                ('diluted_eps_ttm', models.FloatField(null=True)),
                ('quarterly_earning_growth_yoy', models.FloatField(null=True)),
                ('quarterly_revenue_growth_yoy', models.FloatField(null=True)),
                ('analyst_target_price', models.FloatField(null=True)),
                ('trailing_pe', models.FloatField(null=True)),
                ('forward_pe', models.FloatField(null=True)),
                ('price_to_sales_ratio_ttm', models.FloatField(null=True)),
                ('price_to_book_ratio', models.FloatField(null=True)),
                ('ev_to_revenue', models.FloatField(null=True)),
                ('ev_to_ebitda', models.FloatField(null=True)),
                ('beta', models.FloatField(null=True)),
                ('p52_week_high', models.FloatField(null=True)),
                ('p52_week_low', models.FloatField(null=True)),
                ('p50_day_moving_average', models.FloatField(null=True)),
                ('p200_day_moving_average', models.FloatField(null=True)),
                ('shares_outstanding', models.BigIntegerField(null=True)),
                ('shares_float', models.BigIntegerField(null=True)),
                ('shares_short', models.BigIntegerField(null=True)),
                ('shares_short_prior_month', models.BigIntegerField(null=True)),
                ('short_ratio', models.FloatField(null=True)),
                ('short_percent_outstanding', models.FloatField(null=True)),
                ('short_percent_float', models.FloatField(null=True)),
                ('percent_insiders', models.FloatField(null=True)),
                ('percent_institutions', models.FloatField(null=True)),
                ('forword_annual_dividend_rate', models.FloatField(null=True)),
                ('forword_annual_dividend_yield', models.FloatField(null=True)),
                ('payout_ratio', models.FloatField(null=True)),
                ('dividend_date', models.DateTimeField(null=True)),
                ('exdividend_date', models.DateTimeField(null=True)),
                ('last_split_factor', models.CharField(max_length=255, null=True)),
                ('last_split_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
