# Generated by Django 3.1.6 on 2021-03-06 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overview',
            name='tid',
        ),
        migrations.AddField(
            model_name='overview',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 8, 48, 22, 356159)),
        ),
    ]
