# Generated by Django 3.1.6 on 2021-03-06 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('overviews', '0002_auto_20210306_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overview',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
